configmap:
  mongo_url: "mongodb://mongodb:27017/catalogue"
deployment:
  relicas: "1"
  imageName: "220719767845.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue"
  imageVersion: "1.1.0"
  cause: "this version is 1.1.0"
