name: feature pipeline
on: workflow_dispatch

jobs:
  feature-pipeline:
    if: github.ref_main =! "main"
    uses: krishna-33s/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'

